export type FieldConfig = { name: string; label: string; type: 'text' | 'textarea' | 'select'; required?: boolean; options?: string[] };
export type ServiceSeed = { slug: string; title: string; shortDescription: string; description: string; basePrice: string; fieldsConfig: FieldConfig[]; promptTemplate: string };
export const serviceSeeds: ServiceSeed[] = [
  { slug: 'marketplace-cards', title: 'Карточки товаров для маркетплейсов', shortDescription: 'Коммерческие карточки для Ozon, Wildberries и Яндекс Маркета.', description: 'Подготовим структуру, тексты и визуальные варианты карточек товара с фокусом на продажи.', basePrice: '4900', fieldsConfig: [
    ['productName','Название товара','text'],['marketplace','Маркетплейс','select'],['category','Категория','text'],['targetAudience','Целевая аудитория','textarea'],['benefits','Преимущества','textarea'],['offerText','Оффер','textarea'],['style','Стиль','text'],['colors','Цвета','text'],['requiredTexts','Обязательные тексты','textarea'],['additionalNotes','Дополнительно','textarea']
  ].map(([name,label,type]) => ({ name, label, type: type as FieldConfig['type'], required: name !== 'additionalNotes', options: name==='marketplace' ? ['Ozon','Wildberries','Яндекс Маркет','Другое'] : undefined })), promptTemplate: 'Создать продающие карточки товара для маркетплейса с читаемой типографикой и понятной визуальной иерархией.' },
  { slug: 'vk-design', title: 'Оформление сообщества ВК', shortDescription: 'Обложки, аватары и визуальный стиль для сообщества.', description: 'Соберём современное оформление ВК с учётом ниши, аудитории и бренд-материалов.', basePrice: '5900', fieldsConfig: [
    ['communityName','Название сообщества','text'],['communityTopic','Тематика','text'],['vkUrl','Ссылка на ВК','text'],['businessDescription','Описание бизнеса','textarea'],['targetAudience','Целевая аудитория','textarea'],['style','Стиль','text'],['colors','Цвета','text'],['logoAvailability','Есть ли логотип','select'],['coverText','Текст на обложке','textarea'],['additionalNotes','Дополнительно','textarea']
  ].map(([name,label,type]) => ({ name, label, type: type as FieldConfig['type'], required: name !== 'additionalNotes', options: name==='logoAvailability' ? ['Да','Нет','Нужно предложить'] : undefined })), promptTemplate: 'Разработать оформление сообщества ВК: обложка, аватар и визуальная система для первого экрана.' },
  { slug: 'logos', title: 'Логотипы', shortDescription: 'Концепции логотипа с человеческой редактурой.', description: 'Подготовим несколько направлений логотипа для бренда, продукта или проекта.', basePrice: '7900', fieldsConfig: [
    ['brandName','Название бренда','text'],['businessArea','Сфера бизнеса','text'],['brandDescription','Описание бренда','textarea'],['targetAudience','Целевая аудитория','textarea'],['logoType','Тип логотипа','select'],['style','Стиль','text'],['colors','Цвета','text'],['usagePlaces','Где будет использоваться','textarea'],['forbiddenElements','Что нельзя использовать','textarea'],['additionalNotes','Дополнительно','textarea']
  ].map(([name,label,type]) => ({ name, label, type: type as FieldConfig['type'], required: name !== 'additionalNotes', options: name==='logoType' ? ['Текстовый','Знак + текст','Эмблема','Не знаю'] : undefined })), promptTemplate: 'Создать коммерчески применимые концепции логотипа с ясной формой и масштабируемостью.' },
  { slug: 'banners', title: 'Баннеры', shortDescription: 'Баннеры для рекламы, сайта и соцсетей.', description: 'Сделаем баннеры под конкретную площадку, оффер и целевое действие.', basePrice: '3900', fieldsConfig: [
    ['bannerPurpose','Цель баннера','text'],['placementPlatform','Площадка','text'],['sizes','Размеры','text'],['topic','Тема','text'],['offer','Оффер','textarea'],['bannerText','Текст баннера','textarea'],['cta','CTA','text'],['style','Стиль','text'],['colors','Цвета','text'],['brandFiles','Бренд-файлы','textarea'],['additionalNotes','Дополнительно','textarea']
  ].map(([name,label,type]) => ({ name, label, type: type as FieldConfig['type'], required: name !== 'additionalNotes' })), promptTemplate: 'Создать баннер с сильной композицией, читаемым текстом и понятным призывом к действию.' }
];
